name: Response File Change Notifier

on:
  push:
    paths:
      - response.txt

jobs:
  notify-change:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send webhook notification
      run: |
        TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
        echo "Time: $TIMESTAMP"
        TEXTSTAMP="response.txt file changed at '$TIMESTAMP'"
        echo TEXTSTAMP
        //curl -X POST -H "Content-Type: application/json" -d "{""text"":""response.txt file changed at '$TIMESTAMP'""}" https://proxyserver2-sandy.vercel.app/api/webhook
        //curl -X POST -H "Content-Type: application/json" -d "{\"text\":\"response.txt file changed at $TIMESTAMP\"}" https://proxyserver2-sandy.vercel.app/api/webhook
        curl -X POST -H "Content-Type: application/json" -d "{\"text\":\"$TEXTSTAMP\"}" https://proxyserver2-sandy.vercel.app/api/webhook

