name: Response File Change Notifier

on:
  push:
    paths:
      - response.txt

jobs:
  notify-change:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update index.html
      run: |
        TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
        echo "Response file changed at $TIMESTAMP" > sse-index.html
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add index.html
        git commit -m "Update index.html with change notification"
        git push
