name: Update Request File

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to fetch'
        required: true

jobs:
  update-request-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Show received inputs
      run: |
        echo "Received URL: ${{ github.event.inputs.url }}"

    - name: Update request file
      run: |
        URL=${{ github.event.inputs.url }}
        echo "$URL" > request.txt
        //# Clear the content of response.txt
        //> response.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add request.txt response.txt
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m 'Update request.txt and clear response.txt'
          git push https://x-access-token:${{ secrets.GH_OMA }}@github.com/pietupai/hae.git
        fi

    - name: Fetch URL content and update response file
      run: |
        URL=${{ github.event.inputs.url }}
        echo "Fetching content from URL: $URL"
        CONTENT=$(curl -s $URL)
        echo "$CONTENT" > response.txt
        git add response.txt
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m 'Update response.txt'
          git push https://x-access-token:${{ secrets.GH_OMA }}@github.com/pietupai/hae.git
        fi
